### ISSUE TITLE
Node-module node-sass error

### ISSUE THREAD

**Issue by mohamedTechLab** [thoughtworks/build-your-own-radar#53]
Hi guys,

I tried to host the radar on my own server by doing the npm install. But it seems like the module node-sass is not compatible with the latest version.

See the error below:

```bash
ERROR in ENOENT: no such file or directory, scandir '/var/www/html/apps/build-your-own-radar/node_modules/node-sass/vendor'
 @ ./src/stylesheets/base.scss 4:14-127

ERROR in ./src/stylesheets/base.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/var/www/html/apps/build-your-own-radar/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (/var/www/html/apps/build-your-own-radar/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/var/www/html/apps/build-your-own-radar/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/html/apps/build-your-own-radar/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/html/apps/build-your-own-radar/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/var/www/html/apps/build-your-own-radar/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/var/www/html/apps/build-your-own-radar/node_modules/node-sass/lib/index.js:14:35)
```
     
The same error is also given here:

```bash
ERROR in ./src/stylesheets/base.scss
```

Can you please help?

**Comment by SARAN-thala** [comment]
Hi @mohamedTechLab,
It looks like node-sass [issue](https://github.com/sass/node-sass/issues/1579).

```
npm rebuild node-sass
```
run the above command after `npm install`, it'll fix the issue.

**Comment by mohamedTechLab** [comment]
Hi @SARAN-thala ,

Thnks for the reply. 
That fixed the error for me. The files are build in dist wight. When i try to open the index.html i get an empty page. Am i doing something wrong? I want to host the project to my server and run the Techradar there.

**Comment by SARAN-thala** [comment]
Closing this Issue
