### ISSUE TITLE
Failed to install with `npm install`

### ISSUE THREAD

**Issue by GustavZ** [thoughtworks/build-your-own-radar#78]
System: macOS High Sierra

Installing the package with `npm install`or `sudo npm install` fails with following error:

```
> fsevents@1.2.4 install /Users/USER/dev/build-your-own-radar/node_modules/fsevents
> node install

node-pre-gyp ERR! Completion callback never invoked! 
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/11.6.0/bin/node" "/Users/USER/dev/build-your-own-radar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/USER/dev/build-your-own-radar/node_modules/fsevents
node-pre-gyp ERR! node -v v11.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

> cypress@3.1.3 postinstall /Users/USER/dev/build-your-own-radar/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 3.1.3)

internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: EACCES: permission denied, open '/Users/USER/dev/build-your-own-radar/node_modules/cypress/cypress.zip'
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 6

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.1.3 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@3.1.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/USER/.npm/_logs/2019-03-05T09_57_52_217Z-debug.log
```

The last lines in the log file regarding the warn and the error don't deliver much information either:

```
3315 warn acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
3316 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
3317 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
3317 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 6
3318 verbose optional SKIPPING OPTIONAL DEPENDENCY:
3318 verbose optional Failed at the fsevents@1.2.4 install script.
3318 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
3319 verbose stack Error: cypress@3.1.3 postinstall: `node index.js --exec install`
3319 verbose stack Exit status 1
3319 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
3319 verbose stack     at EventEmitter.emit (events.js:188:13)
3319 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3319 verbose stack     at ChildProcess.emit (events.js:188:13)
3319 verbose stack     at maybeClose (internal/child_process.js:978:16)
3319 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
3320 verbose pkgid cypress@3.1.3
3321 verbose cwd /Users/USER/dev/build-your-own-radar
3322 verbose Darwin 17.7.0
3323 verbose argv "/usr/local/Cellar/node/11.6.0/bin/node" "/usr/local/bin/npm" "install"
3324 verbose node v11.6.0
3325 verbose npm  v6.5.0
3326 error code ELIFECYCLE
3327 error errno 1
3328 error cypress@3.1.3 postinstall: `node index.js --exec install`
3328 error Exit status 1
3329 error Failed at the cypress@3.1.3 postinstall script.
3329 error This is probably not a problem with npm. There is likely additional logging output above.
3330 verbose exit [ 1, true ]
```

Does someone know what causes this error?

**Comment by GustavZ** [comment]
Resolved this by:
- Reinstalling npm from: `https://nodejs.org/en/download/`
- force clean the npm cache with: `npm cache clean --force`
- newly ran: `npm install `(NO sudo!)
- fixed audits with: `npm audit fix`
