### ISSUE TITLE
server build for 'build-your-own-radar' fails to compile

### ISSUE THREAD

**Issue by bharathnatarajan1** [thoughtworks/build-your-own-radar#83]
Trying to host 'build-your-own-radar' on a server, it keeps failing with below errors:

Commands tried:
1)  npm run dev
2) npm rebuild node-sass && npm run dev
3) npm install && npm rebuild node-sass && npm run dev

Let me know what can be done to resolve this error?

Error Log:
> build-your-own-radar@0.3.0 dev C:\users\dave\development\build-your-own-radar
> webpack-dev-server --mode development --inline

i ｢wds｣: Project is running at http://0.0.0.0:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\users\dave\development\build-your-own-radar\dist
× ｢wdm｣: Hash: 714ac5ccf39ffc08cfff
Version: webpack 4.28.1
Time: 5398ms
Built at: 03/21/2019 4:15:43 PM
                                  Asset       Size  Chunks             Chunk Names
         common.714ac5ccf39ffc08cfff.js    366 KiB  common  [emitted]  common
                             error.html   1.07 KiB          [emitted]
                     images/favicon.ico   1.12 KiB          [emitted]
                        images/logo.png   5.52 KiB          [emitted]
                images/radar_legend.png   5.92 KiB          [emitted]
              images/search-logo-2x.svg   1.68 KiB          [emitted]
images/tech-radar-landing-page-wide.png   16.1 KiB          [emitted]
                     images/tw-logo.png   3.64 KiB          [emitted]
                             index.html  732 bytes          [emitted]
           main.714ac5ccf39ffc08cfff.js   5.96 MiB    main  [emitted]  main
Entrypoint main = main.714ac5ccf39ffc08cfff.js
Entrypoint common = common.714ac5ccf39ffc08cfff.js
 [0] multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js 40 bytes {main} [built]
[13] multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/common.js 40 bytes {common} [built]
 [./node_modules/loglevel/lib/loglevel.js] C:/Users/dave/development/build-your-own-radar/node_modules/loglevel/lib/loglevel.js 7.68 KiB {main} {common} [built]
 [./node_modules/strip-ansi/index.js] C:/Users/dave/development/build-your-own-radar/node_modules/strip-ansi/index.js 161 bytes {main} {common} [built]
 [./node_modules/url/url.js] C:/Users/dave/development/build-your-own-radar/node_modules/url/url.js 22.8 KiB {main} {common} [built]
 [./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080] (webpack)-dev-server/client?http://0.0.0.0:8080 7.78 KiB {main} {common} [built]
 [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} {common} [built]
 [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} {common} [built]
 [./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} {common} [built]
 [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} {common} [built]
 [./src/common.js] 199 bytes {main} {common} [built]
 [./src/images/favicon.ico] 64 bytes {main} {common} [built]
 [./src/images/logo.png] 61 bytes {main} [built]
 [./src/images/radar_legend.png] 69 bytes {main} [built]
 [./src/site.js] 172 bytes {main} [built]
    + 1129 hidden modules

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/base64-js/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\base64-js\index.js
    Used by 1 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\buffer\index.js
* C:\users\dave\development\build-your-own-radar\node_modules\base64-js\index.js
    Used by 1 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\buffer\index.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/base64-js/index.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/buffer/index.js
 @ ./node_modules/htmlparser2/lib/WritableStream.js
 @ ./node_modules/htmlparser2/lib/index.js
 @ ./node_modules/sanitize-html/dist/index.js
 @ ./src/util/inputSanitizer.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/buffer/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\buffer\index.js
    Used by 27 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\htmlparser2\lib\WritableStream.js
* C:\users\dave\development\build-your-own-radar\node_modules\buffer\index.js
    Used by 10 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\chance\chance.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/buffer/index.js
 @ ./node_modules/htmlparser2/lib/WritableStream.js
 @ ./node_modules/htmlparser2/lib/index.js
 @ ./node_modules/sanitize-html/dist/index.js
 @ ./src/util/inputSanitizer.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/buffer/node_modules/isarray/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\buffer\node_modules\isarray\index.js
    Used by 1 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\buffer\index.js
* C:\users\dave\development\build-your-own-radar\node_modules\buffer\node_modules\isarray\index.js
    Used by 1 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\buffer\index.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/buffer/node_modules/isarray/index.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/buffer/index.js
 @ ./node_modules/htmlparser2/lib/WritableStream.js
 @ ./node_modules/htmlparser2/lib/index.js
 @ ./node_modules/sanitize-html/dist/index.js
 @ ./src/util/inputSanitizer.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/core-util-is/lib/util.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\core-util-is\lib\util.js
    Used by 10 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\stream-browserify\node_modules\readable-stream\lib\_stream_readable.js
* C:\users\dave\development\build-your-own-radar\node_modules\core-util-is\lib\util.js
    Used by 1 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\verror\lib\verror.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/core-util-is/lib/util.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-browserify/node_modules/readable-stream/lib/_stream_readable.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-browserify/node_modules/readable-stream/readable-browser.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-browserify/index.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/tabletop/src/tabletop.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/ieee754/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\ieee754\index.js
    Used by 1 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\buffer\index.js
* C:\users\dave\development\build-your-own-radar\node_modules\ieee754\index.js
    Used by 1 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\buffer\index.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/ieee754/index.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/buffer/index.js
 @ ./node_modules/htmlparser2/lib/WritableStream.js
 @ ./node_modules/htmlparser2/lib/index.js
 @ ./node_modules/sanitize-html/dist/index.js
 @ ./src/util/inputSanitizer.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/inherits/inherits_browser.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\inherits\inherits_browser.js
    Used by 47 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\stream-http\lib\response.js
* C:\users\dave\development\build-your-own-radar\node_modules\inherits\inherits_browser.js
    Used by 4 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\htmlparser2\lib\WritableStream.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/inherits/inherits_browser.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-http/lib/response.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-http/index.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/tabletop/src/tabletop.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/process/browser.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\process\browser.js
    Used by 16 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\stream-http\lib\response.js
* C:\users\dave\development\build-your-own-radar\node_modules\process\browser.js
    Used by 11 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\tabletop\src\tabletop.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/process/browser.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-http/lib/response.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-http/index.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/tabletop/src/tabletop.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/safe-buffer/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\safe-buffer\index.js
    Used by 39 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\string_decoder\lib\string_decoder.js
* C:\users\dave\development\build-your-own-radar\node_modules\safe-buffer\index.js
    Used by 5 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\request\lib\helpers.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/safe-buffer/index.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/string_decoder/lib/string_decoder.js
 @ ./node_modules/htmlparser2/lib/WritableStream.js
 @ ./node_modules/htmlparser2/lib/index.js
 @ ./node_modules/sanitize-html/dist/index.js
 @ ./src/util/inputSanitizer.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/setimmediate/setImmediate.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\setimmediate\setImmediate.js
    Used by 1 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\timers-browserify\main.js
* C:\users\dave\development\build-your-own-radar\node_modules\setimmediate\setImmediate.js
    Used by 1 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\timers-browserify\main.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/setimmediate/setImmediate.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/timers-browserify/main.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-browserify/node_modules/readable-stream/lib/_stream_writable.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-browserify/node_modules/readable-stream/writable-browser.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-browserify/index.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/tabletop/src/tabletop.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/timers-browserify/main.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\timers-browserify\main.js
    Used by 2 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\stream-browserify\node_modules\readable-stream\lib\_stream_writable.js
* C:\users\dave\development\build-your-own-radar\node_modules\timers-browserify\main.js
    Used by 2 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\request\lib\helpers.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/timers-browserify/main.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-browserify/node_modules/readable-stream/lib/_stream_writable.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-browserify/node_modules/readable-stream/writable-browser.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-browserify/index.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/tabletop/src/tabletop.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in (webpack)/buildin/global.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\webpack\buildin\global.js
    Used by 19 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\node-libs-browser\node_modules\punycode\punycode.js
* C:\users\dave\development\build-your-own-radar\node_modules\webpack\buildin\global.js
    Used by 11 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\lodash\core.js
 @ (webpack)/buildin/global.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/node-libs-browser/node_modules/punycode/punycode.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/url/url.js
 @ (webpack)-dev-server/client?http://0.0.0.0:8080
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in (webpack)/buildin/module.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\webpack\buildin\module.js
    Used by 2 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\node-libs-browser\node_modules\punycode\punycode.js
* C:\users\dave\development\build-your-own-radar\node_modules\webpack\buildin\module.js
    Used by 5 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\lodash\core.js
 @ (webpack)/buildin/module.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/node-libs-browser/node_modules/punycode/punycode.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/url/url.js
 @ (webpack)-dev-server/client?http://0.0.0.0:8080
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

WARNING in C:/Users/dave/development/build-your-own-radar/node_modules/xtend/immutable.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\dave\development\build-your-own-radar\node_modules\xtend\immutable.js
    Used by 1 module(s), i. e.
    C:\Users\dave\development\build-your-own-radar\node_modules\stream-http\index.js
* C:\users\dave\development\build-your-own-radar\node_modules\xtend\immutable.js
    Used by 1 module(s), i. e.
    C:\users\dave\development\build-your-own-radar\node_modules\sanitize-html\dist\index.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/xtend/immutable.js
 @ C:/Users/dave/development/build-your-own-radar/node_modules/stream-http/index.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/tabletop/src/tabletop.js
 @ ./src/util/factory.js
 @ ./src/site.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/site.js

ERROR in ./src/stylesheets/base.scss (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--5-2!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js!./src/stylesheets/base.scss)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (C:\users\dave\development\build-your-own-radar\node_modules\sass-loader\lib\loader.js:46:72)
    at runLoaders (C:\Users\dave\development\build-your-own-radar\node_modules\webpack\lib\NormalModule.js:301:20)
    at C:\Users\dave\development\build-your-own-radar\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\dave\development\build-your-own-radar\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at runSyncOrAsync (C:\Users\dave\development\build-your-own-radar\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (C:\Users\dave\development\build-your-own-radar\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (C:\Users\dave\development\build-your-own-radar\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (C:\Users\dave\development\build-your-own-radar\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at provider (C:\Users\dave\development\build-your-own-radar\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)
    at C:\Users\dave\development\build-your-own-radar\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 @ ./src/stylesheets/base.scss 2:14-249
 @ ./src/common.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/common.js
Child html-webpack-plugin for "error.html":
     1 asset
    Entrypoint undefined = error.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/error.html] 1.24 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] 497 bytes {0} [built]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 900 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] 497 bytes {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-2!node_modules/postcss-loader/src/index.js??postcss!node_modules/sass-loader/lib/loader.js!src/stylesheets/base.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/sass-loader/lib/loader.js!./src/stylesheets/base.scss] ./node_modules/css-loader/dist/cjs.js??ref--5-2!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js!./src/stylesheets/base.scss 528 bytes {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./src/stylesheets/base.scss (./node_modules/css-loader/dist/cjs.js??ref--5-2!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js!./src/stylesheets/base.scss)
    Module build failed (from ./node_modules/sass-loader/lib/loader.js):
    Error: Cannot find module 'node-sass'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
        at Function.Module._load (internal/modules/cjs/loader.js:508:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
        at Object.sassLoader (C:\users\dave\development\build-your-own-radar\node_modules\sass-loader\lib\loader.js:46:72)
i ｢wdm｣: Failed to compile.

**Comment by bharathnatarajan1** [comment]
Even tried to fix this error using command 'npm rebuild node-sass' but the error did not resolve.

**Comment by bharathnatarajan1** [comment]
node version - 6.4.1
OS: Windows 7 Enterprise

**Comment by bharathnatarajan1** [comment]
Radar started working after I hosted it in a RHEL 7.X box, seems tech radar is not comaptible with Windows 7. closing this issue for now.
